
github:
  prebuilds:
    master: true  # enable for the default branch (defaults to true)
    branches: true  # enable for all branches in this repo (defaults to false)
    pullRequests: true  # enable for pull requests coming from this repo (defaults to true)
    pullRequestsFromForks: false # enable for pull requests coming from forks (defaults to false)
    addCheck: false # add a check to pull requests (defaults to true)
    addComment: false # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addBadge: true # add a "Review in Gitpod" button to the pull request's description (defaults to false)

image:
  file: .devcontainer/gitpod.Dockerfile
  context: ./.devcontainer
checkoutLocation: "gitpod-experiment"
workspaceLocation: "gitpod-experiment"
tasks:
  - before: |
      ansible-galaxy role install -r ./.devcontainer/ansible/roles/requirements.yml
      ansible-playbook -c localhost ./.devcontainer/ansible/playbooks/setup.yml -e username=gitpod

    init: |
      pre-commit install

    command: |
      zsh ;
      echo "Welcome to the preconfigured development environment! ✌️"

vscode:
  extensions:
    - redhat.ansible
    - ms-azuretools.vscode-docker
    - mhutchie.git-graph
    - eamodio.gitlens
