---
# Author: Michael Bischof <michael@nextpart.io>
# Organization: Nextpart Security Intelligence GmbH
name: $(Date:yyyyMMdd)$(Rev:.r) - Image builds

variables:
  - group: general
  - group: docker

trigger:
  branches:
    include:
      - main
      - dev

schedules:
  - cron: "0 0 * * SUN"
    displayName: Weekly build
    branches:
      include:
        - main

pool: $(agentPool)

jobs:
  - job: ImageBuild
    strategy:
      matrix:
        package:
          playbook: "package"

    steps:
      - checkout: self
        fetchDepth: 1

      - bash: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install ansible
        displayName: Install dependencies

      - bash: |
          ansible-galaxy install -r roles/requirements.yml
          packer init docker
          packer build \
            --var='ansible_playbook=$(playbook)' \
            --var='docker_image_name=splunk-$(playbook)' \
            --var='docker_image_tag=latest' \
            --var='docker_registry=$(dockerHubRegistry)' \
            generic.pkr.hcl
        displayName: Build docker images
      
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: DockerHub
      
      - task: Docker@2
        displayName: Push image to DockerHub
        inputs:
          containerRegistry: DockerHub
          repository: "$(dockerHubRegistry)/splunk-$(playbook)"
          command: push
          tags: |
            latest
