---
- name: Create user
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Add users
      ansible.builtin.user:
        name: "splunk"

    - name: Display the config
      debug:
        msg: |

          Version:      {{ ansible_version.full }}
          Hostname:     {{ ansible_hostname }}
          OS:           {{ ansible_os_family }}
          Distribution: {{ ansible_distribution }}
